CREATE SCHEMA IF NOT EXISTS myschema;

CREATE TABLE IF NOT EXISTS myschema.users (
    id SERIAL PRIMARY KEY,
    uname VARCHAR(10) UNIQUE NOT NULL,
    pword VARCHAR(6) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
